syntax = "proto3";

package byte.v.forge.sms.providers.smsbower.v1;

import "google/protobuf/timestamp.proto";
import "byte/v/forge/contracts/sms/v1/sms.proto";
import "byte/v/forge/sms/internal/v1/sms_internal.proto";

option csharp_namespace = "ByteVForge.Sms.Providers.SmsBower.V1";
option go_package = "github.com/byte-v-forge/sms/gen/go/byte/v/forge/sms/providers/smsbower/v1;smsbowerv1";
option java_multiple_files = true;
option java_outer_classname = "SmsBowerProto";
option java_package = "com.bytevforge.sms.providers.smsbower.v1";
option php_namespace = "ByteVForge\\Sms\\Providers\\SmsBower\\V1";

enum SmsBowerOrderStatusCode {
  SMS_BOWER_ORDER_STATUS_CODE_UNSPECIFIED = 0;
  SMS_BOWER_ORDER_STATUS_CODE_READY = 1;
  SMS_BOWER_ORDER_STATUS_CODE_RETRY_GET = 3;
  SMS_BOWER_ORDER_STATUS_CODE_COMPLETE = 6;
  SMS_BOWER_ORDER_STATUS_CODE_CANCEL = 8;
}

message SmsBowerProviderConfig {
  byte.v.forge.sms.internal.v1.SmsProviderConfig config = 1;
  reserved 2, 3;
}

message SmsBowerGetNumberRequest {
  string upstream_service_key = 1;
  int32 country_id = 2;
  reserved 3, 4;
  string provider_id = 5;
  reserved 6 to 8;
}

message SmsBowerAccessNumberResponse {
  string order_id = 1;
  string phone_number = 2;
}

message SmsBowerGetNumberV2Response {
  string order_id = 1;
  string phone_number = 2;
  byte.v.forge.contracts.sms.v1.DecimalMoney order_cost = 3;
  string country_code = 4;
  bool can_get_another_sms = 5;
  google.protobuf.Timestamp order_time = 6;
  string order_operator = 7;
}

message SmsBowerGetStatusRequest {
  string order_id = 1;
}

message SmsBowerGetStatusResponse {
  string raw_status = 1;
  string code = 2;
  string last_code = 3;
}

message SmsBowerSetStatusRequest {
  string order_id = 1;
  SmsBowerOrderStatusCode status = 2;
}

message SmsBowerSetStatusResponse {
  string raw_status = 1;
}

message SmsBowerCountry {
  byte.v.forge.contracts.sms.v1.SmsCountry country = 1;
  int32 country_id = 2;
  string russian_name = 3;
  string english_name = 4;
  string chinese_name = 5;
}

message SmsBowerPriceOffer {
  byte.v.forge.contracts.sms.v1.SmsPriceOffer offer = 1;
  string provider_id = 2;
  int32 count = 3;
}

message SmsBowerInboundWebhookRequest {
  string order_id = 1;
  string upstream_service_key = 2;
  string message_text = 3;
  string code = 4;
  int32 country_id = 5;
  google.protobuf.Timestamp received_at = 6;
}
